### PR TITLE
BENCH-556_build-docker-with-ubuntu

### PR DESCRIPTION
**Pull request by manuel-cc**
It fixes the docker file for alertmanager2hangoutschat. Following of this PR: https://github.com/Pix4D/terraform-tomato/pull/377

### CODE REVIEW

**Comment by wagdav** [comment]
Do you have an idea why it didn't work with the alpine base image?

**Comment by manuel-cc** [comment]
> Do you have an idea why it didn't work with the alpine base image?

No :( You can find the obscure error message:
```
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

**Comment by aledegano** [comment]
The base image for `ubuntu` is 12 times bigger than that of `alpine` :(
Can we stop a second and understand what's wrong with the alpine one, please?

**Comment by manuel-cc** [comment]
> The base image for `ubuntu` is 12 times bigger than that of `alpine` :(
> Can we stop a second and understand what's wrong with the alpine one, please?

Do you know how to test it and understand what is not working ?

**Comment by aledegano** [comment]
> > The base image for `ubuntu` is 12 times bigger than that of `alpine` :(
> > Can we stop a second and understand what's wrong with the alpine one, please?
> 
> Do you know how to test it and understand what is not working ?

Okay, I've understood what's going on:
If you look at the Makefile the build command reads: `CGO_ENABLED=0 GOOS=linux go build`.
And it is indeed CGO that doesn't work on Alpine.
If you build the binary with that it will work on Alpine too.
**However**
Looking around these files I've also found where the original author publish the official Docker images: https://quay.io/repository/fortnox/alertmanager2hangoutschat.
So I think you should be able to use that one in Nomad and be done with that.

**Comment by odormond** [comment]
> > The base image for `ubuntu` is 12 times bigger than that of `alpine` :(
> > Can we stop a second and understand what's wrong with the alpine one, please?
> 
> Do you know how to test it and understand what is not working ?

To get a shell into the container, just pass `--entrypoint sh` to override the defined one.

```console
+olivier@DES-CH-101-LIN:~/Pix4D/git/alertmanager2hangoutschat$ docker run -ti --rm --entrypoint sh 4e1e9ac67953
/ # /alertmanager2hangoutschat 
sh: /alertmanager2hangoutschat: not found
/ # ldd alertmanager2hangoutschat 
        /lib64/ld-linux-x86-64.so.2 (0x7fec3e3ca000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fec3e3ca000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fec3e3ca000)
Error relocating alertmanager2hangoutschat: __vfprintf_chk: symbol not found
Error relocating alertmanager2hangoutschat: __fprintf_chk: symbol not found
```

That probably means it doesn't like to be built against the host ubuntu and used with the alpine c lib.

**Pull request closed without merging**
